postgres:
  image: postgres:9.4.4
  ports:
    - "5433:5432"
  volumes:
    - .:/app
    - ./db/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: postgres

elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"